const productsData = [
  { id: 1, name: "Classic Cotton Kurti", brand: "FabIndia", price: 1200, discount: 20, image: "/assets/kurti1.jpg", category: "Kurti", description: "Comfortable cotton kurti perfect for casual wear." },
  { id: 2, name: "Floral Maxi Dress", brand: "Biba", price: 2500, discount: 0, image: "/assets/floralmaxi1.png", category: "Dresses", description: "Elegant floral maxi dress for parties." },
  { id: 3, name: "Chiffon Saree", brand: "Saree.com", price: 3500, discount: 20, image: "/assets/chiffonsaree1.png", category: "Saree", description: "Lightweight chiffon saree for festive occasions." },
  { id: 4, name: "Denim Jacket", brand: "Levis", price: 2999, discount: 0, image: "/assets/Denimjacket2.PNg", category: "Jackets", description: "Classic denim jacket for everyday style." },
  { id: 5, name: "Leather Handbag", brand: "Caprese", price: 3999, discount: 0, image: "/assets/Leatherbag1.png", category: "Bags", description: "Premium leather handbag for daily use." },
  { id: 6, name: "Silk Scarf", brand: "W", price: 799, discount: 0, image: "/assets/Silkscarf2.png", category: "Accessories", description: "Soft silk scarf to complement your outfit." },
  { id: 7, name: "Casual Top", brand: "H&M", price: 1099, discount: 20, image: "/assets/casualtops1.jpeg", category: "Tops", description: "Stylish casual top for everyday wear." },
  { id: 8, name: "Pleated Skirt", brand: "Zara", price: 2200, discount: 0, image: "/assets/Pleatedskirt2.png", category: "Bottoms", description: "Elegant pleated skirt for work or party." },
  { id: 9, name: "Sports Leggings", brand: "Nike", price: 1500, discount: 0, image: "/assets/sportslegging2.png", category: "Activewear", description: "Comfortable leggings for sports or gym." },
  { id: 10, name: "Running Shoes", brand: "Adidas", price: 3200, discount: 0, image: "/assets/RunningShoes.png", category: "Shoes", description: "High-performance running shoes." },
  { id: 11, name: "Formal Blouse", brand: "Van Heusen", price: 1800, discount: 0, image: "/assets/formalblouse1.png", category: "Tops", description: "Smart blouse suitable for office wear." },
  { id: 12, name: "Evening Gown", brand: "Global Desi", price: 4500, discount: 0, image: "/assets/eveninggown1.png", category: "Dresses", description: "Beautiful evening gown for special events." },
  { id: 13, name: "Casual Sandals", brand: "Bata", price: 999, discount: 0, image: "/assets/Casualsandals1.png", category: "Footwear", description: "Comfortable sandals for daily wear." },
  { id: 14, name: "Office Tote Bag", brand: "Hidesign", price: 3500, discount: 0, image: "/assets/Officetotebag2.png", category: "Bags", description: "Spacious tote bag for office essentials." },
  { id: 15, name: "Designer Earrings", brand: "Voylla", price: 799, discount: 0, image: "/assets/earrings2.png", category: "Jewellery", description: "Elegant earrings for parties and functions." },
  { id: 16, name: "Ethnic Jacket", brand: "FabIndia", price: 3200, discount: 0, image: "/assets/ethnicjacket2.png", category: "Jackets", description: "Traditional ethnic jacket for festive occasions." },
  { id: 17, name: "Party Top", brand: "Forever21", price: 1200, discount: 20, image: "/assets/party1.jpg", category: "Tops", description: "Chic top perfect for parties." },
  { id: 18, name: "Ankle Boots", brand: "Clarks", price: 4000, discount: 0, image: "/assets/AnkleBoots 2.png", category: "Shoes", description: "Trendy ankle boots for casual wear." },
  { id: 19, name: "Palazzo Pants", brand: "Biba", price: 1800, discount: 0, image: "/assets/Palazzopants1.PNg", category: "Bottoms", description: "Comfortable palazzo pants for casual and office." },
  { id: 20, name: "Evening Clutch", brand: "Caprese", price: 2500, discount: 0, image: "/assets/Eveningclutch2.png", category: "Bags", description: "Stylish clutch for evening events." },

  // 30 new products (all .jpg)
  { id: 21, name: "Gym T-Shirt", brand: "Puma", price: 899, discount: 10, image: "/assets/gymtshirt1.jpg", category: "Activewear", description: "Breathable t-shirt for gym sessions." },
  { id: 22, name: "Yoga Pants", brand: "Reebok", price: 1200, discount: 15, image: "/assets/yogapants1.jpg", category: "Activewear", description: "Stretchable pants for yoga and fitness." },
  { id: 23, name: "Denim Shorts", brand: "Levis", price: 1600, discount: 0, image: "/assets/denimshorts1.jpg", category: "Bottoms", description: "Stylish denim shorts for casual outings." },
  { id: 24, name: "Winter Sweater", brand: "H&M", price: 2200, discount: 25, image: "/assets/wintersweater1.jpg", category: "Sweaters", description: "Warm sweater for winter." },
  { id: 25, name: "Leather Belt", brand: "Tommy Hilfiger", price: 999, discount: 0, image: "/assets/leatherbelt1.jpg", category: "Accessories", description: "Premium leather belt." },
  { id: 26, name: "Party Dress", brand: "Forever21", price: 2800, discount: 20, image: "/assets/partydress1.jpg", category: "Dresses", description: "Trendy party dress." },
  { id: 27, name: "Handmade Necklace", brand: "Voylla", price: 599, discount: 0, image: "/assets/necklace1.jpg", category: "Jewellery", description: "Elegant handmade necklace." },
  { id: 28, name: "Sneakers", brand: "Nike", price: 3500, discount: 0, image: "/assets/sneakers1.jpg", category: "Shoes", description: "Comfortable casual sneakers." },
  { id: 29, name: "Chinos Pants", brand: "Zara", price: 2100, discount: 10, image: "/assets/chinospants1.jpg", category: "Bottoms", description: "Smart chinos for office or casual." },
  { id: 30, name: "Evening Sandals", brand: "Bata", price: 1499, discount: 0, image: "/assets/eveningsandals1.jpg", category: "Footwear", description: "Perfect evening sandals." },
  { id: 31, name: "Maxi Skirt", brand: "Global Desi", price: 1800, discount: 15, image: "/assets/maxiskirt1.jpg", category: "Bottoms", description: "Flowy maxi skirt." },
  { id: 32, name: "Denim Shirt", brand: "Levis", price: 1999, discount: 0, image: "/assets/denimshirt1.jpg", category: "Shirts", description: "Classic denim shirt." },
  { id: 33, name: "Printed Top", brand: "H&M", price: 1100, discount: 0, image: "/assets/printedtop1.jpg", category: "Tops", description: "Casual printed top." },
  { id: 34, name: "Casual Hoodie", brand: "Puma", price: 2000, discount: 20, image: "/assets/casualhoodie1.jpg", category: "Sweaters", description: "Comfortable casual hoodie." },
  { id: 35, name: "Formal Trousers", brand: "Van Heusen", price: 2500, discount: 0, image: "/assets/formaltrousers1.jpg", category: "Bottoms", description: "Smart trousers for office wear." },
  { id: 36, name: "Party Sandals", brand: "Bata", price: 1299, discount: 10, image: "/assets/partysandals1.jpg", category: "Footwear", description: "Stylish party sandals." },
  { id: 37, name: "Ethnic Kurti", brand: "FabIndia", price: 1500, discount: 20, image: "/assets/ethnickurti1.jpg", category: "Kurti", description: "Traditional ethnic kurti." },
  { id: 38, name: "Designer Ring", brand: "Voylla", price: 499, discount: 0, image: "/assets/ring1.jpg", category: "Jewellery", description: "Elegant designer ring." },
  { id: 39, name: "Denim Skirt", brand: "Levis", price: 1600, discount: 0, image: "/assets/denimskirt1.jpg", category: "Bottoms", description: "Classic denim skirt." },
  { id: 40, name: "Leather Wallet", brand: "Caprese", price: 999, discount: 0, image: "/assets/leatherwallet1.jpg", category: "Accessories", description: "Premium leather wallet." },
  { id: 41, name: "Party Gown", brand: "Global Desi", price: 4200, discount: 15, image: "/assets/partygown1.jpg", category: "Dresses", description: "Elegant party gown." },
  { id: 42, name: "Casual Sneakers", brand: "Adidas", price: 3000, discount: 0, image: "/assets/casualsneakers1.jpg", category: "Shoes", description: "Trendy casual sneakers." },
  { id: 43, name: "Formal Shirt", brand: "Van Heusen", price: 1600, discount: 0, image: "/assets/formalshirt1.jpg", category: "Shirts", description: "Classic office shirt." },
  { id: 44, name: "Evening Clutch", brand: "Caprese", price: 2499, discount: 0, image: "/assets/eveningclutch3.jpg", category: "Bags", description: "Stylish evening clutch." },
  { id: 45, name: "Winter Coat", brand: "Zara", price: 4500, discount: 20, image: "/assets/wintercoat1.jpg", category: "Jackets", description: "Warm winter coat." },
  { id: 46, name: "Sunglasses", brand: "Ray-Ban", price: 2999, discount: 0, image: "/assets/sunglasses1.jpg", category: "Accessories", description: "Stylish sunglasses." },
  { id: 47, name: "Sports Jacket", brand: "Nike", price: 3500, discount: 10, image: "/assets/sportsjacket1.jpg", category: "Jackets", description: "Perfect for workouts and casual." },
  { id: 48, name: "Evening Saree", brand: "Saree.com", price: 3800, discount: 15, image: "/assets/eveningsaree1.jpg", category: "Saree", description: "Elegant evening saree." },
  { id: 49, name: "Casual Cap", brand: "Adidas", price: 799, discount: 0, image: "/assets/casualcap1.jpg", category: "Accessories", description: "Stylish casual cap." },
  { id: 50, name: "Leather Boots", brand: "Clarks", price: 4200, discount: 0, image: "/assets/leatherboots1.jpg", category: "Shoes", description: "Trendy leather boots." }
];

export default productsData;
